@startuml
class PlayerState {
  +PlayerMovementState CurrentPlayerMovementState
  +SetPlayerMovementState(playerMovementState)
  +InGroundedState(): bool
  +IsStateGroundedState(movementState): bool
}
enum PlayerMovementState {
  Idling
  Walking
  Running
  Sprinting
  Jumping
  Falling
  Strafing
}
@enduml
