name: Generate PlantUML diagrams

on:
  push:
    paths:
      - 'Docs/diagrams/**/*.puml'

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate diagrams (Docker + PlantUML)
        run: |
          docker run --rm -v "${{ github.workspace }}:/workspace" plantuml/plantuml -tpng /workspace/Docs/diagrams/*.puml || true

      - name: Commit generated images
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Docs/diagrams/*.png || true
          git commit -m "chore(diagrams): generate diagrams" || echo "No image changes to commit"
          git push
